### PR TITLE
Fix for Big Sur

### PR DESCRIPTION
**Pull request by jeremywiebe**
Found at https://github.com/Homebrew/brew/issues/9329#issuecomment-735296878

### CODE REVIEW

**Comment by porttack** [comment]
Hi Jeremy, I'm planning to stick this into a bottle (and possibly a few other things) to the need for devs to build this formula. And catalina bottles can be installed on bigsur. I'm certainly interested in any thoughts you have.

Note I cannot get this formula to build as-is on bigsur with xcode11. I'm not so sure that is a problem with this formula, but it is for one or two other things. I'm hoping to solve them the same way.

**Comment by jeremywiebe** [comment]
I suspect that for the next while we'll also want to have our dot files set the following env variable: `SYSTEM_VERSION_COMPAT=1` globally also to avoid builds breaking because macOS now reports as version "11.x" instead of "10.x" (https://eclecticlight.co/2020/07/21/big-sur-is-both-10-16-and-11-0-its-official/).

**Comment by jeremywiebe** [comment]
Closing this for now. It's super stale and I think INFRA has this handled.

**Comment by dnerdy** [comment]
It seems like this is still needed. See https://khanacademy.atlassian.net/wiki/spaces/INFRA/pages/2140143763/Setting+up+the+webapp+development+environment+on+M2+Macs.

@yogieric can this change be merged, or is there a reason to hold off?

**Comment by porttack** [comment]
> It seems like this is still needed. See https://khanacademy.atlassian.net/wiki/spaces/INFRA/pages/2140143763/Setting+up+the+webapp+development+environment+on+M2+Macs.
> 
> @yogieric can this change be merged, or is there a reason to hold off?

Thanks! I don't have a M1 mac to test on at the moment, but I think we should merge this.

**Comment by jeremywiebe** [comment]
@yogieric or @dnerdy Feel free to land this (or I can if you want me to take it to completion).

**Comment by porttack** [comment]
I've tested python2 install with current dotfiles and with Mark's instructions (https://khanacademy.atlassian.net/wiki/spaces/INFRA/pages/2140143763/Setting+up+the+webapp+development+environment+on+M2+Macs) and on ventura 13.2.1 with the latest xcode, python2 install works fine both with and without this change.

I'm going to merge this change and then re-test on intel next week. If I run into issues, I'll discuss and consider reverting. (Though I doubt there will be a problem.)

**Comment by dnerdy** [comment]
I think the problem is when the system version is a value like "13.2", and you happen to get lucky that your version has a patch number.

**Pull request merged**
